% تعداد گام‌ها
N = 500;

% آرایه‌ها برای نگهداری x و y
x = zeros(1, N);
y = zeros(1, N);

% مقادیر اولیه (مثلاً)
x(1) = 0.1;
y(1) = 0.1;

% حلقه محاسبه نقاط
for k = 1:N-1
    x(k+1) = y(k)*(1 + sin(0.7 * x(k))) - 1.2 * sqrt(abs(x(k)));
    y(k+1) = 0.21 - x(k);
end

% رسم نقاط
figure
plot(x, y, '.')
xlabel('x_k')
ylabel('y_k')
title('Plot of points generated by the difference equations')
grid on
